### ISSUE TITLE
ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

### ISSUE THREAD

**Issue by brianjmurrell** [sura0111/proxyPac#3]
When I use your extension and add a new proxy setting and paste in a proxy PAC, whenever I enable that setting Chromium complains with a `ERR_MANDATORY_PROXY_CONFIGURATION_FAILED` error.

Any ideas what could be going wrong?

**Comment by brianjmurrell** [comment]
Maybe a problem with my PAC file.  Will investigate it.

**Comment by sura0111** [comment]
Thank you for reaching out. Seems that it's now resolved. If you have any more questions or encounter further challenges, feel free to reach out.
